---
- name: Deploy Spring Boot App with Docker
  hosts: servers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ lookup('env','USER') }}"
        groups: docker
        append: yes

    - name: Build and run container using docker compose v2
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}"
        build: always
        state: present

