---
- name: Deploy Spring Boot App with Docker
  hosts: servers
  become: yes
  gather_facts: no

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ lookup('env','USER') }}"
        groups: docker
        append: yes

    - name: Rebuild and run container using docker compose
      community.docker.docker_compose:
        project_src: "/home/{{ lookup('env','USER') }}/spring-app"
        build: true
        state: present
